### ISSUE TITLE
トップページの画像をクリックしても反応がありません。

### ISSUE THREAD

**Issue by hogehiga** [Minemichi/yomita#78]
こんにちは。読み太を操作しようとしたところ反応がなかったので確認お願いします。

# 概要
トップページの画像をクリックしても反応がない

# 再現手順
1. Firefox 57.0で読み太(<https://yomita.herokuapp.com/>)にアクセスする。
1. 左上の画像をクリックする。

# 期待される結果
クリックした本の表紙が拡大表示され、著者名？が表示される。

# 実際の結果
画面が変化せず、Firefoxの開発者ツールのコンソールタブに、「ReferenceError: event is not defined」と表示される。

よろしくお願いします。

**Comment by hogehiga** [comment]
ローカルで動かしていたやつと勘違いしていたみたいなので閉じます。すみません。

**Comment by e155721** [comment]
あ，良かったです
